In [2]:
list = [1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
import numpy as np

In [6]:
array = np.array(list)

In [7]:
array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
#array cannot have different data types like a list
#benefits of arrays:  functions available for an array

In [11]:
array.mean()

4.5

In [12]:
list.pop()

8

In [14]:
list[1:]

[2, 3, 4, 5, 6, 7]

In [15]:
#Arrays can be sliced
array[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [16]:
array[2:5]

array([3, 4, 5])