In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
import numpy as np

In [6]:
#Convert lists to Arrays for each math operations
ar_revenue = np.array(revenue)
ar_expenses = np.array(expenses)

In [9]:
profit = ar_revenue - ar_expenses

In [10]:
#profit for each month
profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [13]:
#Profit after Tax
after_tax = profit * .7
after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [14]:
#Profit Margin
profit_margin = after_tax / ar_revenue
profit_margin

array([ 0.12116163,  0.17589956, -0.30139698, -0.22233524, -0.05211096,
        0.62743886,  0.49993433,  0.28276199,  0.22608449, -0.10897492,
        0.04309514,  0.52746804])

In [27]:
#Good Months
good_month = after_tax > after_tax.mean()
good_month

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [29]:
#Bad Months
bad_month = after_tax < after_tax.mean()
bad_month

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [19]:
#Best Month
max(after_tax)

8140.678

In [20]:
#Worst Month
min(after_tax)

-2595.4530000000004